import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import bcrypt from "bcryptjs";

const VALID_ROLES = ["SUPER_ADMIN", "REDAKSI", "EDITOR", "REPORTER", "USER"];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function serialize(obj: any): any {
  if (obj === null || obj === undefined) return obj;
  return JSON.parse(
    JSON.stringify(obj, (_, value) =>
      typeof value === "bigint" ? Number(value) : value
    )
  );
}

// ── GET /api/users ────────────────────────────────────────────────────────────
export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const roleParam  = searchParams.get("role");
    const activeOnly = searchParams.get("active") !== "false";

    let query = `
      SELECT id, name, email, role::text, image, "isActive", "createdAt"
      FROM users
      WHERE 1=1
    `;

    const queryParams: unknown[] = [];
    let paramIndex = 1;

    if (activeOnly) {
      query += ` AND "isActive" = true`;
    }

    if (roleParam) {
      const roles = roleParam.split(",").map(r => r.trim().toUpperCase());
      const placeholders = roles.map(() => `$${paramIndex++}`).join(", ");
      query += ` AND role::text IN (${placeholders})`;
      queryParams.push(...roles);
    }

    query += ` ORDER BY name ASC`;

    const users = await prisma.$queryRawUnsafe<unknown[]>(query, ...queryParams);

    return NextResponse.json(serialize(users ?? []));

  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("[GET /api/users]", msg);
    return NextResponse.json(
      { error: "Gagal mengambil data", detail: msg },
      { status: 500 }
    );
  }
}

// ── POST /api/users ───────────────────────────────────────────────────────────
export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { name, email, role, isActive, password } = body;

    // ── Validasi wajib ────────────────────────────────────────────────────
    if (!name || typeof name !== "string" || !name.trim()) {
      return NextResponse.json(
        { error: "Nama lengkap wajib diisi" },
        { status: 400 }
      );
    }

    if (!email || typeof email !== "string" || !email.trim()) {
      return NextResponse.json(
        { error: "Email wajib diisi" },
        { status: 400 }
      );
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email.trim())) {
      return NextResponse.json(
        { error: "Format email tidak valid" },
        { status: 400 }
      );
    }

    if (!role || !VALID_ROLES.includes(role)) {
      return NextResponse.json(
        { error: "Role tidak valid" },
        { status: 400 }
      );
    }

    // ── Cek duplikat email ────────────────────────────────────────────────
    const existing = await prisma.$queryRawUnsafe<unknown[]>(
      `SELECT id FROM users WHERE email = $1`,
      email.toLowerCase().trim()
    );

    if (existing.length > 0) {
      return NextResponse.json(
        { error: "Email sudah terdaftar, gunakan email lain" },
        { status: 409 }
      );
    }

    // ── Generate/hash password ─────────────────────────────────────────────
    // Jika password dikosongkan oleh admin, generate acak yang kuat
    const isAutoGenerated = !password || !password.trim();
    const rawPassword = isAutoGenerated
      ? generateStrongPassword()
      : password.trim();

    if (!isAutoGenerated && rawPassword.length < 6) {
      return NextResponse.json(
        { error: "Password minimal 6 karakter" },
        { status: 400 }
      );
    }

    const hashedPassword = await bcrypt.hash(rawPassword, 12);

    // ── Insert ke database ────────────────────────────────────────────────
    const rows = await prisma.$queryRawUnsafe<unknown[]>(
      `INSERT INTO users (id, name, email, password, role, "isActive", "createdAt", "updatedAt")
       VALUES (gen_random_uuid(), $1, $2, $3, $4::"UserRole", $5, NOW(), NOW())
       RETURNING id, name, email, role::text, "isActive", "createdAt"`,
      name.trim(),
      email.toLowerCase().trim(),
      hashedPassword,
      role,
      isActive !== false  // default true jika tidak dikirim
    );

    if (!rows || rows.length === 0) {
      return NextResponse.json(
        { error: "Gagal membuat pengguna" },
        { status: 500 }
      );
    }

    const newUser = serialize(rows[0]);

    // Kirim tempPassword hanya jika di-generate otomatis (bukan dari input admin)
    return NextResponse.json(
      {
        ...newUser,
        ...(isAutoGenerated && { tempPassword: rawPassword }),
      },
      { status: 201 }
    );

  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("[POST /api/users]", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

// ── Helper: generate password acak yang kuat ──────────────────────────────────
function generateStrongPassword(): string {
  const lower   = "abcdefghijkmnpqrstuvwxyz";
  const upper   = "ABCDEFGHJKLMNPQRSTUVWXYZ";
  const digits  = "23456789";
  const special = "!@#$%&*";

  const all = lower + upper + digits + special;

  // Pastikan minimal ada 1 karakter dari setiap kategori
  let password =
    lower[Math.floor(Math.random() * lower.length)] +
    upper[Math.floor(Math.random() * upper.length)] +
    digits[Math.floor(Math.random() * digits.length)] +
    special[Math.floor(Math.random() * special.length)];

  // Tambah 8 karakter acak lagi → total 12 karakter
  for (let i = 0; i < 8; i++) {
    password += all[Math.floor(Math.random() * all.length)];
  }

  // Acak urutan karakternya agar tidak mudah ditebak
  return password.split("").sort(() => Math.random() - 0.5).join("");
}